---
driver:
  name: docker

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV["CHEF_VERSION"] || '14' %>

platforms:
  - name: <%= ENV["KITCHEN_PLATFORM"] %>
    driver_config:
      use_sudo: false

suites:
  - name: default
    run_list:
      - recipe[bitcoin::<%= ENV["KITCHEN_RECIPE"] %>]
    attributes:
      bitcoin:
        variant: <%= ENV["KITCHEN_VARIANT"] %>
