language: ruby
sudo: required
services:
  - docker
before_install:
  - gem update --system
  - gem install bundler
rvm: 2.5.3
matrix:
  exclude:
    - rvm: 2.5.3
  include:
    - rvm: ruby-head
      env: BUNDLE_WITHOUT=test
    - rvm: 2.4.5
      env: BUNDLE_WITHOUT=test
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=bucash
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=bucash
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=abc
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=abc
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=binary  KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=source  KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=binary  KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=binary  KITCHEN_VARIANT=bucash
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=source  KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=source  KITCHEN_VARIANT=bucash
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=source  KITCHEN_VARIANT=abc
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=binary  KITCHEN_VARIANT=abc
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=package KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=package KITCHEN_VARIANT=xt
  allow_failures:
    - rvm: ruby-head
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=source  KITCHEN_VARIANT=abc # build is currently broken: https://travis-ci.org/infertux/chef-bitcoin/jobs/334315828
script:
  - travis_wait 30 bundle exec rake
