language: ruby
sudo: required
services:
  - docker
before_install:
  - gem update --system
  - gem install bundler
rvm: 2.7.0
matrix:
  exclude:
    - rvm: 2.7.0
  include:
    - rvm: ruby-head
      env: BUNDLE_WITHOUT=test
    - rvm: 2.6.5
      env: BUNDLE_WITHOUT=test

    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=abc
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=bucash
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary  KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=abc
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=bucash
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=unlimited

    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=abc CHEF_VERSION=13.12
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=bucash CHEF_VERSION=13.12
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=core CHEF_VERSION=13.12
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source  KITCHEN_VARIANT=unlimited CHEF_VERSION=13.12
  allow_failures:
    - rvm: ruby-head
script:
  - travis_wait 30 bundle exec rake
