name             'bitcoin'
maintainer       'Cédric Félizard'
maintainer_email 'cedric@felizard.fr'
license          'MIT'
description      'Installs and configures Bitcoin'
source_url       'https://github.com/infertux/chef-bitcoin'
issues_url       'https://github.com/infertux/chef-bitcoin/issues'

version          '1.8.0'
chef_version     '>= 13.3'

supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'freebsd'
